version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: 22ylZBYVesGPfJNaBOfUGEhcbPW_3Y8RvF7T4G4jefh9tNKpx      
            Invoke-WebRequest https://raw.githubusercontent.com/JoseDublin/joseavatar/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1

Hosted File:
Set-LocalUser -Name "administrator" -Password (ConvertTo-SecureString -AsPlainText "Develop1234" -Force)
Get-LocalUser -Name "administrator" | Enable-LocalUser 
Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
tar xf ngrok.zip
Copy ngrok.exe C:\Windows\System32
cmd /c echo ./ngrok.exe authtoken "22ylZBYVesGPfJNaBOfUGEhcbPW_3Y8RvF7T4G4jefh9tNKpx" >a.ps1
cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
.\a.ps1